build: Use bib
CentOS/centos-bootc pull request #277
Opened 2024-02-08 19:33 UTC by cgwalters

- It's not worth shipping around a distinct build container; bootc-image-builder already has all the dependencies we need since https://github.com/osbuild/bootc-image-builder/pull/176/commits/44d15acded8641499ea6b4c5d2acceb1bd9694b2
- I'd like to add a more first-class mechanism in bib to build base images

2024-02-08 19:33 UTC, cgwalters commented
This blocks on https://github.com/osbuild/bootc-image-builder/issues/184

2024-02-09 16:14 UTC, cgwalters commented
cc @lmilbaum - this obsoletes https://github.com/CentOS/centos-bootc-infra FYI

2024-02-09 16:26 UTC, cgwalters commented
Ahh, bib isn't built for all 4 architectures.  We should fix that, it *should* be easy but there is an incredible amount of duplicated yaml for the existing two architectures.  Surely there's a best practice in Tekton for making this as easy as just having a list of architectures?

2024-02-09 22:14 UTC, cgwalters commented
Ahh ok we're going to need to adjust the rhtap build side there to use `--entrypoint` too.

2024-02-11 12:41 UTC, lmilbaum requested changes

2024-02-11 12:41 UTC, lmilbaum commented on renovate.json
> +        "quay.io/centos-bootc/bootc-image-builder"
Is the bib image specified in this repo as a dependency? If not then this change has no impact. Maybe the section should be removed all together.

2024-02-11 18:45 UTC, cgwalters commented
https://github.com/redhat-appstudio/build-definitions/pull/799

2024-02-12 22:49 UTC, rhatdan commented
LGTM
Not sure of test failures.

2024-02-12 22:51 UTC, cgwalters commented
Yep, to get RHTAP to succeed we need the PR linked above

2024-02-14 13:40 UTC, cgwalters commented
OK this one looks good to go, Konflux is working.

2024-02-14 14:01 UTC, rhatdan approved these changes

2024-02-14 14:01 UTC, merged

2024-02-14 14:01 UTC, lmilbaum approved these changes